# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'ACR Login' 
      inputs:
        containerRegistry: 'AutomatedTellerServiceConnection'
        command: 'login'
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'AutomatedTellerServiceConnection'
        repository: 'AutomatedTeller'
        command: 'buildAndPush'
        Dockerfile: '**AutomatedTeller.Api/Dockerfile'
    - task: AzureRmWebAppDeployment@4
      displayName: Deploy To Azure
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Visual Studio Enterprise Subscription – MPN'
        appType: 'webAppContainer'
        WebAppName: 'AutomatedTellerApi'
        DockerNamespace: 'AutomatedTeller'
        DockerRepository: 'automatedteller'
        DockerImageTag: 'latest'